[package]
name = "HapPhase"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-htslib = "0.49.0"
clap = { version = "4.5.4", features = ["derive"] }
pretty_env_logger = "0.5.0"
log = "0.4.22"
ndarray = "0.16.1"
